---
# tasks file for wireguard
- name: Add WireGuard server to inventory
  when: wireguard_mode == "client"
  ansible.builtin.add_host:
    name: wireguard_server
    ansible_host: "{{ server_host }}"
    ansible_user: "{{ server_user }}"
  changed_when: false

- name: Read system timezone
  when: timezone is not defined
  ansible.builtin.slurp:
    src: /etc/timezone
  register: _etc_timezone_b64

- name: Ensure Podman is installed
  become: true
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure iptables kernel module is loaded
  become: true
  community.general.modprobe:
    name: ip_tables
    state: present

- name: Ensure mount points exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ state_mount }}"
    - "{{ config_mount }}"

- name: Configure WireGuard client
  when: wireguard_mode == "client"
  block:
    - name: Fetch client configuration
      delegate_to: wireguard_server
      ansible.builtin.slurp:
        src: "{{ state_mount }}/{{ peer_name }}/{{ peer_name }}.conf"
      register: _client_conf_b64

    - name: Write client configuration
      become: true
      ansible.builtin.copy:
        content: "{{ _client_conf_b64.content | b64decode }}"
        dest: "{{ config_mount }}/{{ peer_name }}.conf"
        mode: "0644"

- name: Run WireGuard container
  become: true
  containers.podman.podman_container:
    name: "{{ container_name }}"
    annotation:
      app: wireguard
      role: "{{ wireguard_mode }}"
    image: "{{ image_repository }}:{{ image_tag }}"
    state: started
    restart_policy: always
    cap_add: "{{ container_capabilities }}"
    sysctl: "{{ container_sysctl[wireguard_mode] }}"
    env: "{{ container_env[wireguard_mode] }}"
    ports: "{{ container_ports[wireguard_mode] }}"
    volumes:
      - "{{ state_mount }}:/config"
      - "{{ config_mount }}:/config/wg_confs"
